package rs.oks.api.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.SourceType;
import org.hibernate.annotations.UpdateTimestamp;

import java.sql.Timestamp;

@Entity
@Table(name = "user")
@Data
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class User {


    // Autogenerated id

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "user_sequence")
    @SequenceGenerator(name = "user_sequence", sequenceName = "user_sequence", allocationSize = 1)
    @Column(name = "id")
    private Long id;


    // Info that wills separate administrator account from regular users

    @NonNull
    @Column(name = "administrator")
    private Boolean administrator = false;


    // Info mapped from Excel table

    @NonNull
    @Column(name = "first_name")
    private String firstName;

    @NonNull
    @Column(name = "last_name")
    private String lastName;

    @NonNull
    @Column(name = "date")
    private String date;

    @NonNull
    @Column(name = "date_of_birth")
    private String dateOfBirth;

    @Column(name = "date_doctor_review")
    private String dateDoctorReview;

    @NonNull
    @Column(name = "payment_method")
    private String paymentMethod;

    @Column(name = "membership_fee")
    private String membershipFee;

    // Has separate table to store this info for all months
    // This info refers to paying monthly memberhship fee
    @Column(name = "payments")
    private String payments;

    // Has separate table to store this info for all months
    @Column(name = "comments")
    private String comments;

    // Has separate table to store this info for all months
    // This info refers to paying camp
    @Column(name = "membership_fees")
    private String membershipFees;

    // Has separate table to store this info for all months
    @Column(name = "training_sessions")
    private String trainingSessions;

    @Column(name = "total_training_sessions")
    private Integer totalTrainingSessions;

    @NonNull
    @Column(name = "phone_number")
    private String phoneNumber;

    @NonNull
    @Column(name = "in_viber_group")
    private String inViberGroup;

    @NonNull
    @Column(name = "access_card")
    private String accessCard;

    @NonNull
    @Column(name = "height")
    private String height;

    // TODO: shold have separate table to store this info for all months
    @NonNull
    @Column(name = "note")
    private String note;

    @NonNull
    @Column(name = "ageGroup")
    private String ageGroup;

    @NonNull
    @Column(name = "email")
    private String email;

    @NonNull
    @Column(name = "password")
    private String password;

    @Column(name = "confirmed")
    private Boolean confirmed;


    // Info used to track

    @NonNull
    @CreationTimestamp(source = SourceType.DB)
    @Column(name = "created_at")
    private Timestamp created_at;

    @NonNull
    @UpdateTimestamp(source = SourceType.DB)
    @Column(name = "updated_at")
    private Timestamp updated_at;

    @Column(name = "last_login")
    private Timestamp last_login;
}