name: CI/CD Pipeline

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn test --file pom.xml

  build_and_push_docker_image:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu

      - name: Build and Push Docker Image
        run: |
          mvn install
          docker build -t oksapi:latest .
          docker push oksapi:latest
